In [68]:
# Run this cell but don't modify it.

%load_ext autoreload
%autoreload 2
from matrix import Matrix, zeroes, identity
import test

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Congratulations! All tests pass. Your Matrix class is working as expected.


In [59]:
X = Matrix([[1,2,3], [4,5,6]])
Y = Matrix([[7,8,9], [10,11,12]])
Z = Matrix([[13, 14],[15,16],[17, 18]])
W = Matrix([[1,2,3], [4,5,6], [7,8,9]])
A = Matrix([[1,2], [4,5]])
print("X = \n", X)
print("Y = \n", Y)
print("Z = \n", Z)
print("W = \n", W)
print("A = \n", A)
print("Det(A) = ", A.determinant())
print("The 5*X = \n", 5*X)
print("The trace of W = \n", W.trace())
print("The transpose of X = \n", X.T())
print("The negative -X = \n", -X)
print("The addition X+Y = \n",X+Y)
print("The subtraction X-Y = \n",X-Y)
print("The subtraction Y-X = \n",Y-X)
print("The multiplication X*Z = \n",X*Z)

X = 
 1  2  3 
4  5  6 

Y = 
 7  8  9 
10  11  12 

Z = 
 13  14 
15  16 
17  18 

W = 
 1  2  3 
4  5  6 
7  8  9 

A = 
 1  2 
4  5 

Det(A) =  -3
The 5*X = 
 5  10  15 
20  25  30 

The trace of W = 
 15
The transpose of X = 
 1  4 
2  5 
3  6 

The negative -X = 
 -1  -2  -3 
-4  -5  -6 

The addition X+Y = 
 8  10  12 
14  16  18 

The subtraction X-Y = 
 -6  -6  -6 
-6  -6  -6 

The subtraction Y-X = 
 6  6  6 
6  6  6 

The multiplication X*Z = 
 94.0  100.0 
229.0  244.0 



In [60]:
print("X = \n", X)
print("Z = \n", Z)
print("X * Z = \n{} \n* \n{} \n= \n{}".format( X, Z, X*Z))

X = 
 1  2  3 
4  5  6 

Z = 
 13  14 
15  16 
17  18 

X * Z = 
1  2  3 
4  5  6 
 
* 
13  14 
15  16 
17  18 
 
= 
94.0  100.0 
229.0  244.0 



In [61]:
result = zeroes(X.h,Z.w)
# iterate through rows of X
for i in range(X.h):
   # iterate through columns of Z
   for j in range(Z.w):
       # iterate through rows of Z
       for k in range(Z.h):
            result[i][j] += X[i][k] * Z[k][j]
result

94.0  100.0 
229.0  244.0 

In [62]:
X * Z

94.0  100.0 
229.0  244.0 

In [63]:
Z.g[:]

[[13, 14], [15, 16], [17, 18]]

In [64]:
m3 = Matrix([[8]])
m3.determinant()

0.125

AttributeError: 'list' object has no attribute 'g'

In [32]:
m3

NameError: name 'm3' is not defined

In [ ]:
zeroes(2,3)

In [ ]:
identity(3)

In [ ]:
X = Matrix([[1,2,3], [4,5,6]])
for r in range(X.h):
    for c in range(X.w):
        X.g[r][c] = - X.g[r][c]
print(X)

In [ ]:
X

In [ ]:
print(-X)

In [ ]:
X.g[1][2]

In [ ]:
X.w

X.w

In [ ]:
# some functionality already exists... here's a demo

m1 = Matrix([
    [1, 2],
    [3, 4]
])

m2 = Matrix([
    [2, 5],
    [6, 1]
])

print("m1 is")
print(m1)

print("m2 is")
print(m2)

print("we've also provided you with a function called zeros")
print("here's what happens when you call zeros(4,2)")
print(zeroes(4,2))

print("we've also provided you with a function called identity")
print("here's identity(3)")
print(identity(3))

print("but not everything works yet!")
print("for example, matrix addition...")
print("run the cell below to see what happens when we try...")

In [ ]:
m1 = Matrix([
    [1, 2],
    [3, 4]
])

m2 = Matrix([
    [2, 5],
    [6, 1]
])

m3 = m1 + m2
print("m1 + m2 is")
print(m3)

In [ ]:
# Try running this code. You should get an assertion error. 
# You will continue to get assertion errors until all the 
# methods in matrix.py are correctly implemented.

# You can open matrix.py by selecting File > Open... 
# and then selecting matrix.py

import test

In [ ]:
# open matrix.py (File > Open...) and start
# implementing matrix methods! 

# when your code passes all the tests you can submit by 
# pressing the SUBMIT button in the lower right corner 
# of this page.